require("globals")
require("plugins")

require("languages.scala").setup()
require("languages.go").setup()
require("languages.html").setup()
require("languages.yaml").setup()
require("languages.typescript").setup()
require("languages.terraform").setup()
require("languages.nix").setup()
